Use Python 3.10

diff --git a/project1/.readthedocs.yaml b/project1/.readthedocs.yaml
--- a/project1/.readthedocs.yaml
+++ b/project1/.readthedocs.yaml
@@ -1,17 +1,20 @@
 version: 2
 
-# build:
-#  jobs:
-#    post_checkout:
-#      # Cancel building pull requests when they do not change project1.
-#      #
-#      # If there are no changes (git diff exits with 0) we force the command to return with 183.
-#      # This is a special exit code on Read the Docs that will cancel the build immediately.
-#      - |
-#        if [ "$READTHEDOCS_VERSION_TYPE" = "external" ] && git diff --quiet origin/monorepo -- project1;
-#        then
-#          exit 183;
-#        fi
+build:
+  os: "ubuntu-20.04"
+  tools:
+    python: "3.10"
+  jobs:
+    post_checkout:
+      # Cancel building pull requests when they do not change project2.
+      #
+      # If there are no changes (git diff exits with 0) we force the command to return with 183.
+      # This is a special exit code on Read the Docs that will cancel the build immediately.
+      - |
+        if [ "$READTHEDOCS_VERSION_TYPE" = "external" ] && git diff --quiet origin/monorepo -- project1;
+        then
+          exit 183;
+        fi
 
 sphinx:
   configuration: project1/conf.py
